# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  weight: 2
  
fr:
  languageCode: fr
  contentDir: content/fr
  weight: 1


