
# Netlify configuration pour site Hugo + HugoBlox + Pagefind

[build]
  command = "pnpm install --verbose --no-frozen-lockfile && hugo mod graph && hugo mod get -u && hugo mod tidy && hugo --gc --minify -b $URL && pnpm dlx pagefind --source public --verbose"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.152.2"
  GO_VERSION = "1.21.5"
  NODE_VERSION = "20"
  HUGO_ENABLEGITINFO = "true"
  HUGO_LOG_I18N_WARNINGS = "true"
  HUGO_LOG_WARNINGS = "true"
  FORCE_COLOR = "1"
  PNPM_LOG_LEVEL = "debug"

[context.production.environment]
  HUGO_ENV = "production"

# Deploy Preview (PRs)
[context.deploy-preview]
  command = "pnpm install --verbose --no-frozen-lockfile && hugo mod get && hugo mod tidy && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --logLevel debug --printI18nWarnings --printPathWarnings && pnpm dlx pagefind --source public --verbose"

# Branch Deploy (branche autre que main)
[context.branch-deploy]
  command = "pnpm install --verbose --no-frozen-lockfile && hugo mod get && hugo mod tidy && hugo --gc --minify -b $DEPLOY_PRIME_URL --logLevel debug --printI18nWarnings --printPathWarnings && pnpm dlx pagefind --source public --verbose"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[plugins.inputs]
  debug = true
